hack worktree support

diff --git a/goclone b/goclone
--- a/goclone
+++ b/goclone
@@ -24,6 +24,7 @@ Arguments:
 
 Examples:
   $ goclone ahmetb/govvv
+  $ goclone k8s.io/kubernetes fixup-branch-a12 # clones a mirror'd GOPATH, with a worktree for branch specified
   $ eval \$(goclone -q k8s.io/kubernetes)
   $ goclone https://github.com/pkg/errors -- cat LICENSE
 EOF
@@ -41,39 +42,29 @@ go_get_url=
 # parse command line arguments
 while getopts qh opt; do
     case "${opt}" in
-		q)
-			quiet="true"
-			;;
-		h)
-			usage; exit 1;;
-		?)
-			echo "Run with \"-h\" for help." >&2
-			exit 1
-	esac
+        q)
+            quiet="true"
+            ;;
+        h)
+            usage; exit 1;;
+        ?)
+            echo "Run with \"-h\" for help." >&2
+            exit 1
+    esac
 done
 shift $((OPTIND - 1))
 
 # at least one positional argument required
 if [[ $# -lt 1 ]]; then
-	echo "$0: missing argument REPO" >&2
-	exit 1
+    echo "$0: missing argument REPO" >&2
+    exit 1
 fi
 
 # first positional argument is the repository
 src="$1"
 shift
 
-# parse the remainder of arguments, preserve them to pass it to the new shell
-while [[ $# -gt 0 ]]; do
-	case "$1" in
-	--)
-		shift;break;;
-	*)
-		echo "$0: unrecognized extra positional argument: $1" >&2
-		exit 1
-	esac
-done
-exeargs=$*
+branch_name="$1"
 
 # is github_user/github_repo
 if [[ "$src" =~ ^([A-Za-z0-9-]+)\/([A-Za-z0-9-]+)$ ]]; then
@@ -97,18 +88,20 @@ elif [[ "$src" =~ ^https?://github\.com/([A-Za-z0-9-]+)\/([A-Za-z0-9-]+)(\.git)?
 # is go-get path (e.g. github.com/user/repo/pkg/subpkg, k8s.io/kubernetes, labix.org/mgo.v1)
 elif [[ "$src" =~ ^([a-zA-Z0-9_\-]+[\.a-zA-Z0-9_\-]+)+(\/[A-Za-z0-9\._\-]+)+$ ]]; then
     go_get_url="$src"
-    repo="${src//[\.\/]/-}" # replace '/' with '-'
+    repo="${src//[\/]/-}" # replace '/' with '-' (and don't replace '.')
 else
     echo "$0: invalid REPO format \"${src}\".">&2
     exit 1
 fi
 
-project="$WORKSPACE/gopath-${repo}"
+project="$WORKSPACE/gopath--${repo}"
+branch_project="$WORKSPACE/gopath--${repo}--${branch_name}"
 clone_path=
 if [[ "$github" == "true" ]]; then
     clone_path="$project/src/github.com/${user}/${repo}"
 else
     clone_path="$project/src/${go_get_url}"
+    branch_clone_path="$branch_project/src/${go_get_url}"
 fi
 
 # TODO(ahmetb) if $GITHUB_USERNAME or ~/.github_username, add a remote called
@@ -147,25 +140,25 @@ if [[ ! -d "${clone_path}" ]]; then
     fi
 fi
 
+if [[ ! -z "${branch_name:-}" ]]; then
+    if [[ ! -d "${branch_project}" ]]; then
+        (
+            cd "${clone_path}"
+            git worktree add "${branch_clone_path}" "${branch_name}"
+        )
+    fi
+    project="${branch_project}"
+    clone_path="${branch_clone_path}"
+fi
+
 if [[ "$quiet" == "true" ]]; then
-	# print commands to prepare env
-	echo "    export GOPATH=\"${project}\";"
-	echo "    export PATH=\"${project}/bin:\${PATH}\";"
-	echo "    cd \"${clone_path}\";"
+    # print commands to prepare env
+    echo "    export GOPATH=\"${project}\";"
+    echo "    export PATH=\"${project}/bin:\${PATH}\";"
+    echo "    cd \"${clone_path}\";"
 else
-	if [[ -n "$exeargs" ]]; then
-	# run command in env
-	(
-		cd "${clone_path}"
-		env GOPATH="${project}" PATH="${project}/bin:${PATH}" $SHELL -c "${exeargs[@]}"
-	)
-	else
-	# start an interactive shell with env
-	(
-		cd "${clone_path}"
-		echo -e "\033[32mgoclone: Starting a new shell in GOPATH=${project}$(tput sgr0)" >&2
-		env GOPATH="${project}" PATH="${project}/bin:${PATH}" $SHELL || true
-		echo -e "\033[32mgoclone: Shell exited.$(tput sgr0)" >&2
-	)
-	fi
+    cd "${clone_path}"
+    echo -e "\033[32mgoclone: Starting a new shell in GOPATH=${project}$(tput sgr0)" >&2
+    env GOPATH="${project}" PATH="${project}/bin:${PATH}" $SHELL || true
+    echo -e "\033[32mgoclone: Shell exited.$(tput sgr0)" >&2
 fi
